#!/bin/sh
DIR="$(dirname "$(readlink -f "$0")")"
if [ -x "$DIR/python/bin/python3" ]; then
    PYTHONPATH="$DIR/lib" exec "$DIR/python/bin/python3" -s "$DIR/check_mail_report.py" "$@"
fi
exec python3 "$DIR/check_mail_report.py" "$@"
